# Copyright (c) 2025 Soares
#
# SPDX-License-Identifier: Apache-2.0

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule: { interval: "weekly" }
    labels: ["deps","ci"]
  - package-ecosystem: "pip"
    directory: "/"
    schedule: { interval: "weekly" }
    labels: ["deps","python"]
